CREATE TABLE USERS (
  USER_ID NUMBER CONSTRAINT PK_USER_ID PRIMARY KEY,
  USER_LOGIN VARCHAR2(8),
  USER_PASSWORD VARCHAR2(12)
);

--Insert employees--
INSERT INTO USERS (USER_ID,USER_LOGIN,USER_PASSWORD)
VALUES(1,'user1','olala');

INSERT INTO USERS (USER_ID,USER_LOGIN,USER_PASSWORD)
VALUES(2,'user2','t0to');

--Create an user 'Actenum' with only reading privileges on the users table--
CREATE PUBLIC SYNONYM USERS FOR USERS;

CREATE USER Actenum IDENTIFIED BY actenum;
GRANT CREATE SESSION to Actenum;
GRANT SELECT ON USERS TO Actenum;